name: Android CI

on:
  pull_request:
    branches: ['**']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Set up Gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', 'gradle.properties', 'gradle.lockfile') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Android SDK
        uses: android-actions/setup-android@v2

      - name: Download dependencies
        run: ./gradlew build -x test

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

  ui-tests:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'run-ui-tests')
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Install Android SDK
        uses: android-actions/setup-android@v2

      - name: Set up and start emulator
        run: |
          sdkmanager --install "system-images;android-31;google_apis;x86_64"
          echo "no" | avdmanager create avd -n test -k "system-images;android-31;google_apis;x86_64" --force
          nohup emulator -avd test -no-snapshot -no-window -no-audio &
          adb shell input keyevent 82

      - name: Run UI tests
        run: ./gradlew connectedAndroidTest

      - name: Upload UI test results
        uses: actions/upload-artifact@v3
        with:
          name: ui-test-results
          path: |
            **/build/test-results/**/*.xml
            **/build/reports/**

      - name: Annotate test results
        uses: dorny/test-reporter@v1
        with:
          name: Unit Tests
          path: '**/build/test-results/testDebugUnitTest/**/*.xml'
          reporter: junit
